# Basic Python

## 1. Split this string

In [3]:
s = "Hi there Sam!"

In [6]:
x=s.split()
print(x)    


['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
planet = "Earth"
diameter = 12742

In [8]:
print("The diameter of"+planet+"is",diameter,"kilometer");

The diameter ofEarthis 12742 kilometer


## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [10]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [11]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [14]:
import numpy as np

In [15]:
array=np.arange(20,35,2)
print("Array of all integers form 20 to 35")
print(array)

Array of all integers form 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
import numpy as np

In [17]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [18]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
arr=np.stack((a,b),axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [19]:
import pandas as pd


In [22]:
data=[['tom',10],['nick',15],['juli',14]]
df=pd.DataFrame(data,columns=['name','age'])
df

name  age
0   tom   10
1  nick   15
2  juli   14

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [27]:
import pandas as pd
from dateutil.parser import parse
date_series=pd.Series(['Jan 2023' , 'Feb 2023'])
print("Original Series:")
print(date_series)

Original Series:
0    Jan 2023
1    Feb 2023
dtype: object


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [28]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [29]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [31]:
df=pd.DataFrame(lists,columns=['number','letter','number'])
print(df)

   number letter  number
0       1    aaa      22
1       2    bbb      25
2       3    ccc      24
